version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - rm -rf node_modules
      - npm install
  build:
    commands:
artifacts: 
  files:
    - '**/*'
